event/project/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SelectField,RadioField,IntegerField


class FilterForm(FlaskForm):
    criteria = SelectField("Select",choices=[("","Select..."),("country","Country"),("state","State"),("keyword","Keyword")])
    filter_word=StringField("Enter text")
    geo=RadioField('Use My Location',choices=[("1","My Location")])
    radius=IntegerField()
    # from_date=StringField("Enter text")

event/__init__.py
from flask import Flask
import json
import os
from event.config import Config
from api.api import *
from models.graph import Graph

graph= Graph()


def create_app(config_class=Config):

    """Sets up the application ans returns a flask application instance"""
    app = Flask(__name__)
    app.config.from_object(config_class)
    from event.project.routes import event
    app.register_blueprint(event)

    
        # print(load_events_from_db_to_graph(graph).get_vertices())



    return(app)

event/project/routes.py
from flask import Blueprint, render_template,session,request,redirect,url_for,flash
from event import graph
from api.api import *
from api.helpers import *
from datetime import datetime
event = Blueprint("event", __name__)

from .forms import FilterForm

@event.route('/', methods=['POST', 'GET'])
def home():
   
    filter_word=request.args.get('filter_word')
    criteria=request.args.get('criteria')
    geo=request.args.get('geo')
    radius=request.args.get('radius')
    keyword=request.args.get('keyword')



    if filter_word is None:
        criteria = 'country'
        filter_word = 'united states'

    data={criteria:filter_word}
    print(f'Data is {data}')
    if keyword:
        data.update({'keyword':keyword})
    if radius:
        data.update({'radius':radius})

    if geo:
        data.update({'lat':session['latitude']})
        data.update({'lon':session['longitude']})
        print(f"After geo is true data is {data}")
       
    form = FilterForm()
    events= filter_dups(delegator(**data))


    return render_template('home.html',events=events,form=form)


@event.route('/about')
def about():
    return render_template('about.html')

@event.route('/geo/<lon>/<lat>')
def set_geolocation(lon,lat):
    session['longitude']=lon
    session['latitude']=lat
    return {"resp":"OK"}

event/templates/about.html
{%extends "layout.html"%}
{%block content%}
<div class= "about">
    <h1>My about page</h1>
    <p>This is a test website</p>
</div>
{%endblock%}

event/templates/home.html
{% extends "layout.html" %}
{% block content %}
        {%for event in events%}
            <div class="col-md-3">
            <article class="media content-section">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{event.url}}">{{event.name}}</a>
                <!-- <small class="text-muted">{{event.title}}</small> -->
              </div>
              <img class="article-img" src="{{event.images}}">
              <p class="article-content">{{event.dates}}</p>

            </div>
          </article>
        </div>
        {%endfor%}

{% endblock content %}

event/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}"> -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

</head>
<body>
    <main role="main" class="container">
      <div class="row">
          {%with messages= get_flashed_messages(with_categories=true)%}
            {%if messages%}
              {%for category,message in messages%}
                <div class="alert alert-{{category}}">
                  {{message}}
                </div>
              {%endfor%}
            {%endif%}
          {%endwith%}
          <div class="col-md-12 mb-4">
            <form class="form-inline" method="GET" action="{{url_for('event.home')}}">
              {{form.criteria(class="form-control mr-2")}}
              {{form.filter_word(class="form-control ml-1", placeholder="Enter filter")}}
              {{form.radius(class="form-control ml-1", placeholder="Enter radius")}}
              {{form.geo(class="form-control ml-1")}}
              <button type="submit" class="btn btn-primary ml-5">Filter</button>
            </form>
          </div>
          {% block content %}{% endblock %}
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

    <script>
      var div  = document.getElementById("location");
      function getLocation() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(showPosition, showError);
        } else {
          div.innerHTML = "The Browser Does not Support Geolocation";
        }
      }

      function showPosition(position) {

        fetch('/geo/'+position.coords.longitude+'/'+position.coords.latitude).then(function(response){
              response.json().then(function(data){
              });
            });
      }

      function showError(error) {
        if(error.PERMISSION_DENIED){
            div.innerHTML = "The User have denied the request for Geolocation.";
        }
      }
      getLocation();
    </script>